# Generated by Django 5.2.4 on 2025-08-11 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='acitvity_level',
            new_name='activity_level',
        ),
    ]
